In [41]:
import numpy as np
import math

In [42]:
x = np.zeros((10,10))

In [43]:
x[1][1] = 1

x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [43]:
result = np.where(x == 1)
r = [(result[0][x],result[1][x]) for x in range(len(result[0]))]
points = list(itertools.combinations(r,2))
points

[((1, 1), (2, 2)), ((1, 1), (7, 5)), ((2, 2), (7, 5))]

In [44]:
def distance(first_point, second_point):
    x_squared = math.pow(first_point[0] - second_point[0],2)
    y_squared = math.pow(first_point[1]-second_point[1],2)
    d = math.sqrt(x_squared + y_squared)
    return d

In [48]:
import itertools
def interpolate(numpy_map,max_distance):
    cooridinates = np.where(numpy_map == 1)
    r = [(cooridinates[0][x],cooridinates[1][x]) for x in range(len(cooridinates[0]))]
    points = list(itertools.combinations(r,2))
    for point in points:
        point_one = point[0]
        point_two = point[1]
        d = distance(point_one, point_two)
        if d < max_distance:
            m = (point_two[0] - point_one[0])/(point_two[1] - point_one[1])
            b =  point_one[0] - (m*point_one[1])
            diff = abs(point_one[1] - point_two[1])
            for x in range(min(point_one[1],point_two[1]) + 1,max(point_one[1],point_two[1])):
                y = (m*x) + b
                y_floor = math.floor(y)
                y_ceil = math.ceil(y)
                numpy_map[y_floor][x] = 1
                numpy_map[y_ceil][x] = 1
            
    return numpy_map

In [17]:
def join(numpy_map,point_one,point_two):
    #assume point[y][x]
    m = (point_two[0] - point_one[0])/(point_two[1] - point_one[1])
    b =  point_one[0] - (m*point_one[1])
    diff = abs(point_one[1] - point_two[1])
    for x in range(min(point_one[1],point_two[1]) + 1,max(point_one[1],point_two[1])):
        y = (m*x) + b
        y_floor = math.floor(y)
        y_ceil = math.ceil(y)
        numpy_map[y_floor][x] = 1
        numpy_map[y_ceil][x] = 1
    return 

In [184]:

n = interpolate(x,10)
    

In [190]:
n

array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0.]])

In [186]:
# def add_clearance(numpy_map,threshold):
#     cooridinates = np.where(numpy_map == 1)
#     r = [(cooridinates[0][x],cooridinates[1][x]) for x in range(len(cooridinates[0]))]
#     shape_x,shape_y = numpy_map.shape[1],numpy_map.shape[0]
#     for point in r:
#         y = point[0]
#         x = point[1]
#         for i in range(1,threshold+1):
            
#             numpy_map[y,x:min(x+i+1,shape_x)] = 1
#             numpy_map[y,max(x-i,0):x] = 1
#             numpy_map[y:min(y+i+1,shape_y),x] = 1
#             numpy_map[max(y-i,0):y,x] = 1
            
#     return numpy_map
        
    

In [38]:
def add_clearance(numpy_map,threshold):
    cooridinates = np.where(numpy_map == 1)
    r = [(cooridinates[0][x],cooridinates[1][x]) for x in range(len(cooridinates[0]))]
    shape_x,shape_y = numpy_map.shape[1],numpy_map.shape[0]
    for point in r:
        y = point[0]
        x = point[1]
        numpy_map[max(y-threshold,0):min(y + threshold+1,shape_y),max(x-threshold,0):min(x+threshold+1,shape_x)] = 1
    return numpy_map
        
    

In [44]:
f = add_clearance_2(x,2)
f

array([[1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [133]:
x = np.zeros((2,10))

In [134]:
x[0][5:0:-1] = 1

In [135]:
x[0]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [147]:
n

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [154]:
n

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [163]:
n[0][0:2] = 1
n[0][0:0] = 1
n[0:2][0] = 1
# n[0:0][0] = 1

In [164]:
n

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [160]:
n[0][0:0] = 1

In [174]:
n[0:2]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

array([0., 1., 1., 0.])

In [196]:
import time

In [219]:
time.time?

In [223]:
from typing import  Protocol

ImportError: cannot import name 'Protocol'

In [232]:
from typing import Dict, List, Iterator, Tuple, TypeVar, Optional
from typing_extensions import Protocol
T = TypeVar('T')


Location = TypeVar('Location')
class Graph(Protocol):
    def neighbors(self, id: Location) -> List[Location]: pass


class WeightedGraph(Graph):
    def cost(self, from_id: Location, to_id: Location) -> float: pass
    
    
import heapq

class PriorityQueue:
    def __init__(self):
        self.elements: List[Tuple[float, T]] = []

    def empty(self) -> bool:
        return not self.elements

    def put(self, item: T, priority: float):
        heapq.heappush(self.elements, (priority, item))

    def get(self) -> T:
        return heapq.heappop(self.elements)[1]


def a_star_search(graph: WeightedGraph, start: Location, goal: Location):
    frontier = PriorityQueue()
    frontier.put(start, 0)
    came_from: Dict[Location, Optional[Location]] = {}
    cost_so_far: Dict[Location, float] = {}
    came_from[start] = None
    cost_so_far[start] = 0

    while not frontier.empty():
        current: Location = frontier.get()

        if current == goal:
            break

        for next in graph.neighbors(current):
            new_cost = cost_so_far[current] + graph.cost(current, next)
            if next not in cost_so_far or new_cost < cost_so_far[next]:
                cost_so_far[next] = new_cost
                priority = new_cost + heuristic(next, goal)
                frontier.put(next, priority)
                came_from[next] = current

    return came_from, cost_so_far


def reconstruct_path(came_from: Dict[Location, Location],
                     start: Location, goal: Location) -> List[Location]:
    current: Location = goal
    path: List[Location] = []
    while current != start:
        path.append(current)
        current = came_from[current]
    path.append(start) # optional
    path.reverse() # optional
    return path

GridLocation = Tuple[int, int]

def heuristic(a: GridLocation, b: GridLocation) -> float:
    (x1, y1) = a
    (x2, y2) = b
    return abs(x1 - x2) + abs(y1 - y2)

In [229]:
Protocol?

NameError: name 'PriorityQueue' is not defined

In [233]:
GridLocation = Tuple[int, int]

class SquareGrid:
    def __init__(self, width: int, height: int):
        self.width = width
        self.height = height
        self.walls: List[GridLocation] = []
    
    def in_bounds(self, id: GridLocation) -> bool:
        (x, y) = id
        return 0 <= x < self.width and 0 <= y < self.height
    
    def passable(self, id: GridLocation) -> bool:
        return id not in self.walls
    
    def neighbors(self, id: GridLocation) -> Iterator[GridLocation]:
        (x, y) = id
        neighbors = [(x+1, y), (x-1, y), (x, y-1), (x, y+1)] # E W N S
        # see "Ugly paths" section for an explanation:
        if (x + y) % 2 == 0: neighbors.reverse() # S N W E
        results = filter(self.in_bounds, neighbors)
        results = filter(self.passable, results)
        return results

'/Users/zaid/tdAmeritrade/key_levels'